server:
  port: 5503
  host: localhost
auth:
  jwksUri: http://localhost:5501/.well-known/jwks.json
database:
  url: mongodb+srv://vighneshpawar004:toE5w3cfHDzER9Vo@cluster0.28ofqde.mongodb.net/order?retryWrites=true&w=majority&appName=Cluster0
kafka:
  broker: localhost:9092